from typing import Protocol, AsyncIterator, List, Optional, Dict
from app.chat.domain.models import Session, Message

class ILLMConnection(Protocol):
    """Protocol for streaming text from a Language Model."""
    def stream_chat(
        self,
        model: str,
        messages: List[Dict[str, str]],
        max_tokens: int,
    ) -> AsyncIterator[str]:
        ...
    async def close(self) -> None:
        ...

class IChatRepository(Protocol):
    """Protocol for chat persistence operations."""
    async def get_all_sessions(self) -> List[Session]: ...
    async def create_session(self, session_id: str, title: str) -> Session: ...
    async def get_session_by_id(self, session_id: str, load_messages: bool = False) -> Optional[Session]: ...
    async def update_session_title(self, session: Session, new_title: str) -> Session: ...
    async def create_message(self, session_id: str, role: str, content: str, raw_content: Optional[str] = None) -> Message: ...
    async def delete_session(self, session_id: str) -> bool: ...
