"""LLM interface contracts.

Defines the protocol for the LLM application service.
Consumers should depend on this abstraction rather than the concrete service.
"""

from __future__ import annotations

from typing import AsyncGenerator, Protocol, runtime_checkable


@runtime_checkable
class ILLMService(Protocol):
    """Structural contract for the LLM Application Service.

    Any object that provides `stream_response` with the correct signature
    satisfies this Protocol.
    """

    def stream_response(
        self,
        raw_history: list[dict[str, str]]
    ) -> AsyncGenerator[str, None]:
        """Stream a response from the LLM based on the chat history.

        Args:
            raw_history: The raw chat history before pruning.

        Yields:
            Chunks of text as they are generated by the LLM.
        """
        ...
